### ISSUE TITLE
[FEATURE REQUEST] Console log if only put one letter and pressed Reverse button.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#1]

**Comment by vitika9** [comment]
Instead of logging only if there is only one letter, isn't it a better idea to log if the inserted text is [palindrome](https://en.wikipedia.org/wiki/Palindrome)? I can implement this if you like.

**Comment by KendallDoesCoding** [comment]
I replied on this one via email, I say Yes. 

@HamzaYehia is already made a PR to go ahead with this, so merging that (#4)

**Comment by KendallDoesCoding** [comment]
Sure.
