### ISSUE TITLE
[FEAT] Allow user to see output on "Enter"

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#10]
Currently, the user has to tap the "Reverse" button to see the output (Reversed text). It would be great if it was made so that, when the user presses the "Enter" key on their keyboard after typing the text, the output will automatically show up.

Currently, if you try pressing enter, it just refreshes the page.

**Comment by mohameddjebloun** [comment]
Hey, I think I can fix this issue using a keypress event listener and checking if it's "Enter" , Assign me to it if the issue is still open

**Comment by KendallDoesCoding** [comment]
> Hey, I think I can fix this issue using a keypress event listener and checking if it's "Enter" , Assign me to it if the issue is still open

Assigned!
