### ISSUE TITLE
Update Functionality: "COPY" text button.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#13]
When the user copy's text o the reversed text once it is reversed, it will copy the reversed text (as it's meant to). Although, if you try copying without reversing the text it copies:   .

If the text isn't reversed yet, and the copy button is clicked. It would be nice, if the button will not copy anything to clipboard, instead console log saying "Text was not reversed, hence text not copied".

**Comment by brandonbyr4** [comment]
Would you like it to have an alert when there is no text?  For example alert("Please enter text before copying.")

**Comment by KendallDoesCoding** [comment]
> Would you like it to have an alert when there is no text? For example alert("Please enter text before copying.")

We can do that, or we can just put that in the console. But, ig a alert would make better sense!

**Comment by YusufAgca** [comment]
hi,
I think it makes more sense to have the copy button disabled, unless the reverse button is pressed.

**Comment by brandonbyr4** [comment]
These are all separate issues.

**Comment by KendallDoesCoding** [comment]
Hi Yusuf. That is exactly what this issue plans to do. Although, we will
add a alert or console log after doing this.

**Comment by mohameddjebloun** [comment]
Hey I think that I can help with this issue 
The fixes I'm thinking of doing are the following:
Disable the copy button until reverse is clicked.
If the text input is empty then clicking the reverse button will alert instead
Please assign me for this issue and tell me if I should know anything about running it locally and contributing.

**Comment by KendallDoesCoding** [comment]
> Hey I think that I can help with this issue The fixes I'm thinking of doing are the following: Disable the copy button until reverse is clicked. If the text input is empty then clicking the reverse button will alert instead Please assign me for this issue and tell me if I should know anything about running it locally and contributing.

Assigned
