### ISSUE TITLE
Text inside copy button not properly visible

### ISSUE THREAD

**Issue by ajayanuragi** [KendallDoesCoding/backward-text#17]
I think the color of the text " Copy" Inside button should be white, and not blackish.

**Comment by KendallDoesCoding** [comment]
Sorry for the huge delay on replying.. Yes, I agree. Can you make the changes and submit a PR? @ajayanuragi

**Comment by ajayanuragi** [comment]
Yes, I will

**Comment by KendallDoesCoding** [comment]
> Yes, I will

Thank you.

**Comment by KendallDoesCoding** [comment]
@ajayanuragi Any update? also the text is actually black when you hover over it

**Comment by KendallDoesCoding** [comment]
fixed in #22
