### ISSUE TITLE
Improve design/interface

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#2]
The website looks kinda ugly rn, the design requires to be changed to look nice and believable, because this is a real product and people can actually win the prizes mentioned, no scam :)

**Comment by zabihhaqqani** [comment]
Hi @KendallDoesCoding can I work on this?

**Comment by KendallDoesCoding** [comment]
> Hi @KendallDoesCoding can I work on this?

Sure! Assigned you.

**Comment by zabihhaqqani** [comment]
![2](https://user-images.githubusercontent.com/53895282/183128293-e34ac6d9-8eed-487f-93e2-d12d9df5f1d7.JPG)

Thank you for assigning it to me!!

I have done some changes if more changes are needed do let me know will do it.

**Comment by zabihhaqqani** [comment]
If the changes are fine I will send a pull request.

**Comment by zabihhaqqani** [comment]
Can I send a pull request?

**Comment by KendallDoesCoding** [comment]
Yes, please.

**Comment by zabihhaqqani** [comment]
I have sent a Pull request.
