### ISSUE TITLE
[FEAT] Add Google Fonts

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#20]
The fonts look quite ugly as of now. Add Google Fonts

**Comment by Adejuwon-00** [comment]
I would be happy to take on the task of adding Google Fonts to improve the overall aesthetics of the website. Please let me know if there are any specific fonts or styles that you would like me to consider or if you have any preferences.

**Comment by KendallDoesCoding** [comment]
> I would be happy to take on the task of adding Google Fonts to improve the overall aesthetics of the website. Please let me know if there are any specific fonts or styles that you would like me to consider or if you have any preferences.

Assigned. It's up to you, whatever suits the text will work.

**Comment by KendallDoesCoding** [comment]
fixed in #22
