### ISSUE TITLE
[Styling, CSS] Improve design

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#21]
I would like to improve the overall design of the page.

**Comment by Mansi168** [comment]
I would love to work on improving the design part of the website....kindly assign this issue to me..!

**Comment by KendallDoesCoding** [comment]
> I would love to work on improving the design part of the website....kindly assign this issue to me..!

Assigned!

**Comment by KendallDoesCoding** [comment]
@Mansi168 - any update?

**Comment by Mansi168** [comment]
yes, The designing work is ongoing.....will make pr soon..

**Comment by KendallDoesCoding** [comment]
fixed in #23
