### ISSUE TITLE
[FEAT] Change text color of button (CSS)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#24]
Change the text color to White or a light color on "Get Started button". The color on hover of button is perfect!

![image](https://user-images.githubusercontent.com/84712013/226086500-147a83cc-0b9a-4c96-97ed-0f7e84524e70.png)

**Comment by Yashdon999** [comment]
I want to work on this issue

**Comment by KendallDoesCoding** [comment]
@Yashdon999, you deleted your comment?

**Comment by Yashdon999** [comment]
I can Fix the issue of Change text color of button

**Comment by y4sssh** [comment]
i changed the color of the button ok Sir
