### ISSUE TITLE
[DOCS] Update example video in README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/backward-text#25]
in #23 , the design was updated and the old design became outdated.

Update the example video with the new design, etc.

**Comment by y4sssh** [comment]
I want to work on this issue

**Comment by KendallDoesCoding** [comment]
> I want to work on this issue

Sure.

**Comment by B-a-b-u** [comment]
i will take this

**Comment by AiswaryaSgi** [comment]
i will take this

**Comment by SanjayRavichandran-Mscss** [comment]
I will take this issue

**Comment by JJanany** [comment]
i will take this

**Comment by vikashmurugesh** [comment]
i will take this

**Comment by vikashmurugesh** [comment]
i will take this
