### ISSUE TITLE
[Docs] Revamping the Readme

### ISSUE THREAD

**Issue by at-the-vr** [KendallDoesCoding/backward-text#9]
Hey Kendal, what I am thinking of is updating your Readme for [backward-text](https://github.com/KendallDoesCoding/backward-text). In the end it will have Description, GIFs (for demonstration), guidelines to contribiute(if needed). If you want something more lemme know 😉

**Comment by KendallDoesCoding** [comment]
That should work.

**Comment by at-the-vr** [comment]
Hey Kendal, I am so sorry for the huge delay. I have updated your README in this [link](https://github.com/PiseAtharva/backward-text/tree/development). 
If you like this then I will start a PR

**Comment by KendallDoesCoding** [comment]
@PiseAtharva - looks good to me. Please create a PR.

**Comment by at-the-vr** [comment]
Hey Kendal, let me know incase something's off with this PR #18
